# Generated by Django 6.1.1 on 2026-09-14 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('doubt_status', models.CharField(choices=[('none', 'No doubt'), ('open', 'Open'), ('resolved', 'Resolved')], default='none', max_length=10)),
                ('doubt_message', models.TextField(blank=True)),
                ('doubt_raised_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reply', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='questions.question')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_doubts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['doubt_status'], name='progress_qu_doubt_s_791820_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'question'), name='one_progress_per_student_question')],
            },
        ),
    ]
