# Generated by Django 6.1.1 on 2026-09-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionprogress',
            name='answer_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionprogress',
            name='answer_shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
