# Generated by Django 6.1.1 on 2026-09-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_questionprogress_answer_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionprogress',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionprogress',
            name='reply_seen',
            field=models.BooleanField(default=True),
        ),
    ]
