# Generated by Django 6.1.1 on 2026-09-13 19:38

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.LmsUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='access_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_content',
            field=models.BooleanField(default=True, help_text='Admins only: may create, edit and delete courses, topics and questions.'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_students',
            field=models.BooleanField(default=True, help_text='Admins only: may approve, reject and manage students.'),
        ),
        migrations.AddField(
            model_name='user',
            name='request_message',
            field=models.TextField(blank=True, help_text='Optional message from the student when requesting access.'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The admin who approved or rejected this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('main_admin', 'Main Admin')], default='student', max_length=20),
        ),
    ]
