# Generated by Django 6.1.1 on 2026-09-13 19:38

from django.db import migrations


def make_superusers_main_admins(apps, schema_editor):
    """Superusers created before roles existed (like 'mainadmin') become approved Main Admins."""
    User = apps.get_model('users', 'User')
    User.objects.filter(is_superuser=True).update(role='main_admin', access_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_access_status_and_more'),
    ]

    operations = [
        migrations.RunPython(make_superusers_main_admins, migrations.RunPython.noop),
    ]
