# Generated by Django 6.0.5 on 2026-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_make_superusers_main_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Student WhatsApp number, e.g. +971501234567. Collected at registration.', max_length=20),
        ),
    ]
