# Generated by Django 6.0.5 on 2026-09-14 16:43

from django.db import migrations, models


def grant_all_published_courses_to_existing_students(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Course = apps.get_model('courses', 'Course')
    
    published_courses = list(Course.objects.filter(is_published=True))
    if not published_courses:
        return
        
    approved_students = User.objects.filter(role='student', access_status='approved')
    for student in approved_students:
        student.allowed_courses.add(*published_courses)

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_course_level'),
        ('users', '0004_add_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this student is allowed to access.', related_name='allowed_students', to='courses.course'),
        ),
        migrations.RunPython(
            grant_all_published_courses_to_existing_students,
            reverse_code=migrations.RunPython.noop
        ),
    ]
