# Generated by Django 6.1.1 on 2026-09-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_allowed_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(blank=True, choices=[('indigo', 'Indigo'), ('violet', 'Violet'), ('teal', 'Teal'), ('rose', 'Rose'), ('amber', 'Amber'), ('emerald', 'Emerald'), ('sky', 'Sky'), ('slate', 'Slate')], help_text='Background colour of the round profile picture.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_icon',
            field=models.CharField(blank=True, choices=[('initials', 'Initials'), ('fox', 'Fox'), ('panda', 'Panda'), ('owl', 'Owl'), ('penguin', 'Penguin'), ('turtle', 'Turtle'), ('lion', 'Lion'), ('whale', 'Whale'), ('unicorn', 'Unicorn'), ('rocket', 'Rocket'), ('star', 'Star'), ('flame', 'Flame'), ('sprout', 'Sprout')], help_text='Picture inside the avatar. "initials" shows the letters of the name.', max_length=20),
        ),
    ]
