# Generated by Django 6.1.1 on 2026-09-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question students will practise.')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('answer', models.TextField(blank=True, help_text='Model answer or solution. Students can reveal it after trying.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Smaller numbers are shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.topic')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['topic', 'difficulty'], name='questions_q_topic_i_2f996f_idx')],
            },
        ),
    ]
