# Generated by Django 6.1.1 on 2026-09-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, help_text='Model answer or solution. Hidden from students, unless an admin shows it to one student.'),
        ),
    ]
