# Generated by Django 6.1.1 on 2026-09-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='syllabus_points',
            field=models.JSONField(blank=True, default=list, help_text='A list of bullet points covering the subtopics.'),
        ),
    ]
